import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Main from '../components/Main'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Erin Chan | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <div className="py-60">
        <About />
      </div>
      <div className="py-60">
        <Skills />
      </div>
      <div className="py-60">
        <Projects />
      </div>
      <div className="py-60">
        <Contact />
      </div>
    </div>
  )
}
